version: '3.3'

services:
  bot:
    container_name: bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /opt/services/bot/work-bot
    environment:
      - POSTGRES_DB=your_database
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    expose:
      - "5432"
